package model_db;
// Generated Jun 27, 2020 1:59:00 AM by Hibernate Tools 4.3.1



/**
 * OfferInfoDetails generated by hbm2java
 */
public class OfferInfoDetails  implements java.io.Serializable {


     private Integer idofferInfoDetails;
     private OfferInfo offerInfo;
     private String precolumn;
     private String columnDesc;
     private String postcolumn;
     private int position;
     private Integer flag;

    public OfferInfoDetails() {
    }

	
    public OfferInfoDetails(OfferInfo offerInfo, String precolumn, int position) {
        this.offerInfo = offerInfo;
        this.precolumn = precolumn;
        this.position = position;
    }
    public OfferInfoDetails(OfferInfo offerInfo, String precolumn, String columnDesc, String postcolumn, int position, Integer flag) {
       this.offerInfo = offerInfo;
       this.precolumn = precolumn;
       this.columnDesc = columnDesc;
       this.postcolumn = postcolumn;
       this.position = position;
       this.flag = flag;
    }
   
    public Integer getIdofferInfoDetails() {
        return this.idofferInfoDetails;
    }
    
    public void setIdofferInfoDetails(Integer idofferInfoDetails) {
        this.idofferInfoDetails = idofferInfoDetails;
    }
    public OfferInfo getOfferInfo() {
        return this.offerInfo;
    }
    
    public void setOfferInfo(OfferInfo offerInfo) {
        this.offerInfo = offerInfo;
    }
    public String getPrecolumn() {
        return this.precolumn;
    }
    
    public void setPrecolumn(String precolumn) {
        this.precolumn = precolumn;
    }
    public String getColumnDesc() {
        return this.columnDesc;
    }
    
    public void setColumnDesc(String columnDesc) {
        this.columnDesc = columnDesc;
    }
    public String getPostcolumn() {
        return this.postcolumn;
    }
    
    public void setPostcolumn(String postcolumn) {
        this.postcolumn = postcolumn;
    }
    public int getPosition() {
        return this.position;
    }
    
    public void setPosition(int position) {
        this.position = position;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }




}


