package model_db;
// Generated Jun 27, 2020 1:59:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * OfferType generated by hbm2java
 */
public class OfferType  implements java.io.Serializable {


     private Integer idofferType;
     private String offerTypeDesc;
     private Integer flag;
     private Set<OfferInfo> offerInfos = new HashSet<OfferInfo>(0);

    public OfferType() {
    }

	
    public OfferType(String offerTypeDesc) {
        this.offerTypeDesc = offerTypeDesc;
    }
    public OfferType(String offerTypeDesc, Integer flag, Set<OfferInfo> offerInfos) {
       this.offerTypeDesc = offerTypeDesc;
       this.flag = flag;
       this.offerInfos = offerInfos;
    }
   
    public Integer getIdofferType() {
        return this.idofferType;
    }
    
    public void setIdofferType(Integer idofferType) {
        this.idofferType = idofferType;
    }
    public String getOfferTypeDesc() {
        return this.offerTypeDesc;
    }
    
    public void setOfferTypeDesc(String offerTypeDesc) {
        this.offerTypeDesc = offerTypeDesc;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set<OfferInfo> getOfferInfos() {
        return this.offerInfos;
    }
    
    public void setOfferInfos(Set<OfferInfo> offerInfos) {
        this.offerInfos = offerInfos;
    }




}


