package model_db;
// Generated Jun 27, 2020 1:59:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Operator generated by hbm2java
 */
public class Operator  implements java.io.Serializable {


     private Integer idoperator;
     private String operatorDesc;
     private Double transactLimit;
     private Integer flag;
     private Set<SimInfo> simInfos = new HashSet<SimInfo>(0);
     private Set<OfferInfo> offerInfos = new HashSet<OfferInfo>(0);
     private Set<ProviderClient> providerClients = new HashSet<ProviderClient>(0);

    public Operator() {
    }

	
    public Operator(String operatorDesc) {
        this.operatorDesc = operatorDesc;
    }
    public Operator(String operatorDesc, Double transactLimit, Integer flag, Set<SimInfo> simInfos, Set<OfferInfo> offerInfos, Set<ProviderClient> providerClients) {
       this.operatorDesc = operatorDesc;
       this.transactLimit = transactLimit;
       this.flag = flag;
       this.simInfos = simInfos;
       this.offerInfos = offerInfos;
       this.providerClients = providerClients;
    }
   
    public Integer getIdoperator() {
        return this.idoperator;
    }
    
    public void setIdoperator(Integer idoperator) {
        this.idoperator = idoperator;
    }
    public String getOperatorDesc() {
        return this.operatorDesc;
    }
    
    public void setOperatorDesc(String operatorDesc) {
        this.operatorDesc = operatorDesc;
    }
    public Double getTransactLimit() {
        return this.transactLimit;
    }
    
    public void setTransactLimit(Double transactLimit) {
        this.transactLimit = transactLimit;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set<SimInfo> getSimInfos() {
        return this.simInfos;
    }
    
    public void setSimInfos(Set<SimInfo> simInfos) {
        this.simInfos = simInfos;
    }
    public Set<OfferInfo> getOfferInfos() {
        return this.offerInfos;
    }
    
    public void setOfferInfos(Set<OfferInfo> offerInfos) {
        this.offerInfos = offerInfos;
    }
    public Set<ProviderClient> getProviderClients() {
        return this.providerClients;
    }
    
    public void setProviderClients(Set<ProviderClient> providerClients) {
        this.providerClients = providerClients;
    }




}


