package model_db;


import java.util.HashSet;
import java.util.Set;

/**
 * Operator generated by hbm2java
 */
public class Operator  implements java.io.Serializable {


     private Integer idoperator;
     private String operatorDesc;
     private Double transactLimit;
     private Integer flag;
     private Set simInfos = new HashSet(0);
     private Set offerInfos = new HashSet(0);
     private Set providerClients = new HashSet(0);

    public Operator() {
    }

	
    public Operator(String operatorDesc) {
        this.operatorDesc = operatorDesc;
    }
    public Operator(String operatorDesc, Double transactLimit, Integer flag, Set simInfos, Set offerInfos, Set providerClients) {
       this.operatorDesc = operatorDesc;
       this.transactLimit = transactLimit;
       this.flag = flag;
       this.simInfos = simInfos;
       this.offerInfos = offerInfos;
       this.providerClients = providerClients;
    }
   
    public Integer getIdoperator() {
        return this.idoperator;
    }
    
    public void setIdoperator(Integer idoperator) {
        this.idoperator = idoperator;
    }
    public String getOperatorDesc() {
        return this.operatorDesc;
    }
    
    public void setOperatorDesc(String operatorDesc) {
        this.operatorDesc = operatorDesc;
    }
    public Double getTransactLimit() {
        return this.transactLimit;
    }
    
    public void setTransactLimit(Double transactLimit) {
        this.transactLimit = transactLimit;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set getSimInfos() {
        return this.simInfos;
    }
    
    public void setSimInfos(Set simInfos) {
        this.simInfos = simInfos;
    }
    public Set getOfferInfos() {
        return this.offerInfos;
    }
    
    public void setOfferInfos(Set offerInfos) {
        this.offerInfos = offerInfos;
    }
    public Set getProviderClients() {
        return this.providerClients;
    }
    
    public void setProviderClients(Set providerClients) {
        this.providerClients = providerClients;
    }




}


