package model_db;
// Generated Jun 27, 2020 1:59:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PortInfo generated by hbm2java
 */
public class PortInfo  implements java.io.Serializable {


     private Integer idportInfo;
     private StatusInfo statusInfo;
     private String portDesc;
     private Double score;
     private Integer flag;
     private Set<SimInfo> simInfos = new HashSet<SimInfo>(0);

    public PortInfo() {
    }

	
    public PortInfo(StatusInfo statusInfo, String portDesc) {
        this.statusInfo = statusInfo;
        this.portDesc = portDesc;
    }
    public PortInfo(StatusInfo statusInfo, String portDesc, Double score, Integer flag, Set<SimInfo> simInfos) {
       this.statusInfo = statusInfo;
       this.portDesc = portDesc;
       this.score = score;
       this.flag = flag;
       this.simInfos = simInfos;
    }
   
    public Integer getIdportInfo() {
        return this.idportInfo;
    }
    
    public void setIdportInfo(Integer idportInfo) {
        this.idportInfo = idportInfo;
    }
    public StatusInfo getStatusInfo() {
        return this.statusInfo;
    }
    
    public void setStatusInfo(StatusInfo statusInfo) {
        this.statusInfo = statusInfo;
    }
    public String getPortDesc() {
        return this.portDesc;
    }
    
    public void setPortDesc(String portDesc) {
        this.portDesc = portDesc;
    }
    public Double getScore() {
        return this.score;
    }
    
    public void setScore(Double score) {
        this.score = score;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set<SimInfo> getSimInfos() {
        return this.simInfos;
    }
    
    public void setSimInfos(Set<SimInfo> simInfos) {
        this.simInfos = simInfos;
    }




}


