package model_db;
// Generated Jun 27, 2020 1:59:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ServerProfile generated by hbm2java
 */
public class ServerProfile  implements java.io.Serializable {


     private Integer idProfile;
     private StatusInfo statusInfo;
     private UserInfo userInfo;
     private String serverAdress1;
     private String serverAdress2;
     private String serverIp1;
     private String serverIp2;
     private int serverPort1;
     private int serverPort2;
     private Integer flag;
     private Set<Station> stations = new HashSet<Station>(0);

    public ServerProfile() {
    }

	
    public ServerProfile(StatusInfo statusInfo, UserInfo userInfo, String serverAdress1, String serverAdress2, String serverIp1, String serverIp2, int serverPort1, int serverPort2) {
        this.statusInfo = statusInfo;
        this.userInfo = userInfo;
        this.serverAdress1 = serverAdress1;
        this.serverAdress2 = serverAdress2;
        this.serverIp1 = serverIp1;
        this.serverIp2 = serverIp2;
        this.serverPort1 = serverPort1;
        this.serverPort2 = serverPort2;
    }
    public ServerProfile(StatusInfo statusInfo, UserInfo userInfo, String serverAdress1, String serverAdress2, String serverIp1, String serverIp2, int serverPort1, int serverPort2, Integer flag, Set<Station> stations) {
       this.statusInfo = statusInfo;
       this.userInfo = userInfo;
       this.serverAdress1 = serverAdress1;
       this.serverAdress2 = serverAdress2;
       this.serverIp1 = serverIp1;
       this.serverIp2 = serverIp2;
       this.serverPort1 = serverPort1;
       this.serverPort2 = serverPort2;
       this.flag = flag;
       this.stations = stations;
    }
   
    public Integer getIdProfile() {
        return this.idProfile;
    }
    
    public void setIdProfile(Integer idProfile) {
        this.idProfile = idProfile;
    }
    public StatusInfo getStatusInfo() {
        return this.statusInfo;
    }
    
    public void setStatusInfo(StatusInfo statusInfo) {
        this.statusInfo = statusInfo;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public String getServerAdress1() {
        return this.serverAdress1;
    }
    
    public void setServerAdress1(String serverAdress1) {
        this.serverAdress1 = serverAdress1;
    }
    public String getServerAdress2() {
        return this.serverAdress2;
    }
    
    public void setServerAdress2(String serverAdress2) {
        this.serverAdress2 = serverAdress2;
    }
    public String getServerIp1() {
        return this.serverIp1;
    }
    
    public void setServerIp1(String serverIp1) {
        this.serverIp1 = serverIp1;
    }
    public String getServerIp2() {
        return this.serverIp2;
    }
    
    public void setServerIp2(String serverIp2) {
        this.serverIp2 = serverIp2;
    }
    public int getServerPort1() {
        return this.serverPort1;
    }
    
    public void setServerPort1(int serverPort1) {
        this.serverPort1 = serverPort1;
    }
    public int getServerPort2() {
        return this.serverPort2;
    }
    
    public void setServerPort2(int serverPort2) {
        this.serverPort2 = serverPort2;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set<Station> getStations() {
        return this.stations;
    }
    
    public void setStations(Set<Station> stations) {
        this.stations = stations;
    }




}


