package model_db;
// Generated Jun 27, 2020 1:59:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SimInfo generated by hbm2java
 */
public class SimInfo  implements java.io.Serializable {


     private Integer idsimInfo;
     private Operator operator;
     private PortInfo portInfo;
     private SimType simType;
     private StatusInfo statusInfo;
     private String simnumber;
     private String simPinCode;
     private Date dateConsul;
     private Double lastSolde;
     private Double lastEstimatedSolde;
     private Double lastBonus;
     private Double lastEstimatedBonus;
     private Double averageResponseTime;
     private Double lastSignalStrength;
     private Double weightedIndex;
     private Integer totalTransactions;
     private Integer succededTransactions;
     private Integer simTimeout;
     private Integer flag;
     private Set<SimOffer> simOffers = new HashSet<SimOffer>(0);

    public SimInfo() {
    }

	
    public SimInfo(Operator operator, PortInfo portInfo, StatusInfo statusInfo, String simnumber, String simPinCode) {
        this.operator = operator;
        this.portInfo = portInfo;
        this.statusInfo = statusInfo;
        this.simnumber = simnumber;
        this.simPinCode = simPinCode;
    }
    public SimInfo(Operator operator, PortInfo portInfo, SimType simType, StatusInfo statusInfo, String simnumber, String simPinCode, Date dateConsul, Double lastSolde, Double lastEstimatedSolde, Double lastBonus, Double lastEstimatedBonus, Double averageResponseTime, Double lastSignalStrength, Double weightedIndex, Integer totalTransactions, Integer succededTransactions, Integer simTimeout, Integer flag, Set<SimOffer> simOffers) {
       this.operator = operator;
       this.portInfo = portInfo;
       this.simType = simType;
       this.statusInfo = statusInfo;
       this.simnumber = simnumber;
       this.simPinCode = simPinCode;
       this.dateConsul = dateConsul;
       this.lastSolde = lastSolde;
       this.lastEstimatedSolde = lastEstimatedSolde;
       this.lastBonus = lastBonus;
       this.lastEstimatedBonus = lastEstimatedBonus;
       this.averageResponseTime = averageResponseTime;
       this.lastSignalStrength = lastSignalStrength;
       this.weightedIndex = weightedIndex;
       this.totalTransactions = totalTransactions;
       this.succededTransactions = succededTransactions;
       this.simTimeout = simTimeout;
       this.flag = flag;
       this.simOffers = simOffers;
    }
   
    public Integer getIdsimInfo() {
        return this.idsimInfo;
    }
    
    public void setIdsimInfo(Integer idsimInfo) {
        this.idsimInfo = idsimInfo;
    }
    public Operator getOperator() {
        return this.operator;
    }
    
    public void setOperator(Operator operator) {
        this.operator = operator;
    }
    public PortInfo getPortInfo() {
        return this.portInfo;
    }
    
    public void setPortInfo(PortInfo portInfo) {
        this.portInfo = portInfo;
    }
    public SimType getSimType() {
        return this.simType;
    }
    
    public void setSimType(SimType simType) {
        this.simType = simType;
    }
    public StatusInfo getStatusInfo() {
        return this.statusInfo;
    }
    
    public void setStatusInfo(StatusInfo statusInfo) {
        this.statusInfo = statusInfo;
    }
    public String getSimnumber() {
        return this.simnumber;
    }
    
    public void setSimnumber(String simnumber) {
        this.simnumber = simnumber;
    }
    public String getSimPinCode() {
        return this.simPinCode;
    }
    
    public void setSimPinCode(String simPinCode) {
        this.simPinCode = simPinCode;
    }
    public Date getDateConsul() {
        return this.dateConsul;
    }
    
    public void setDateConsul(Date dateConsul) {
        this.dateConsul = dateConsul;
    }
    public Double getLastSolde() {
        return this.lastSolde;
    }
    
    public void setLastSolde(Double lastSolde) {
        this.lastSolde = lastSolde;
    }
    public Double getLastEstimatedSolde() {
        return this.lastEstimatedSolde;
    }
    
    public void setLastEstimatedSolde(Double lastEstimatedSolde) {
        this.lastEstimatedSolde = lastEstimatedSolde;
    }
    public Double getLastBonus() {
        return this.lastBonus;
    }
    
    public void setLastBonus(Double lastBonus) {
        this.lastBonus = lastBonus;
    }
    public Double getLastEstimatedBonus() {
        return this.lastEstimatedBonus;
    }
    
    public void setLastEstimatedBonus(Double lastEstimatedBonus) {
        this.lastEstimatedBonus = lastEstimatedBonus;
    }
    public Double getAverageResponseTime() {
        return this.averageResponseTime;
    }
    
    public void setAverageResponseTime(Double averageResponseTime) {
        this.averageResponseTime = averageResponseTime;
    }
    public Double getLastSignalStrength() {
        return this.lastSignalStrength;
    }
    
    public void setLastSignalStrength(Double lastSignalStrength) {
        this.lastSignalStrength = lastSignalStrength;
    }
    public Double getWeightedIndex() {
        return this.weightedIndex;
    }
    
    public void setWeightedIndex(Double weightedIndex) {
        this.weightedIndex = weightedIndex;
    }
    public Integer getTotalTransactions() {
        return this.totalTransactions;
    }
    
    public void setTotalTransactions(Integer totalTransactions) {
        this.totalTransactions = totalTransactions;
    }
    public Integer getSuccededTransactions() {
        return this.succededTransactions;
    }
    
    public void setSuccededTransactions(Integer succededTransactions) {
        this.succededTransactions = succededTransactions;
    }
    public Integer getSimTimeout() {
        return this.simTimeout;
    }
    
    public void setSimTimeout(Integer simTimeout) {
        this.simTimeout = simTimeout;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set<SimOffer> getSimOffers() {
        return this.simOffers;
    }
    
    public void setSimOffers(Set<SimOffer> simOffers) {
        this.simOffers = simOffers;
    }




}


