package model_db;
// Generated Jun 27, 2020 1:59:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SimOffer generated by hbm2java
 */
public class SimOffer  implements java.io.Serializable {


     private Integer idsimOffer;
     private OfferInfo offerInfo;
     private SimInfo simInfo;
     private UserInfo userInfo;
     private Date dateAffect;
     private Date dateDeactivation;
     private Double limitTransact;
     private Integer flag;
     private Set<TransactionTopup> transactionTopups = new HashSet<TransactionTopup>(0);

    public SimOffer() {
    }

	
    public SimOffer(OfferInfo offerInfo, SimInfo simInfo, UserInfo userInfo, Date dateAffect) {
        this.offerInfo = offerInfo;
        this.simInfo = simInfo;
        this.userInfo = userInfo;
        this.dateAffect = dateAffect;
    }
    public SimOffer(OfferInfo offerInfo, SimInfo simInfo, UserInfo userInfo, Date dateAffect, Date dateDeactivation, Double limitTransact, Integer flag, Set<TransactionTopup> transactionTopups) {
       this.offerInfo = offerInfo;
       this.simInfo = simInfo;
       this.userInfo = userInfo;
       this.dateAffect = dateAffect;
       this.dateDeactivation = dateDeactivation;
       this.limitTransact = limitTransact;
       this.flag = flag;
       this.transactionTopups = transactionTopups;
    }
   
    public Integer getIdsimOffer() {
        return this.idsimOffer;
    }
    
    public void setIdsimOffer(Integer idsimOffer) {
        this.idsimOffer = idsimOffer;
    }
    public OfferInfo getOfferInfo() {
        return this.offerInfo;
    }
    
    public void setOfferInfo(OfferInfo offerInfo) {
        this.offerInfo = offerInfo;
    }
    public SimInfo getSimInfo() {
        return this.simInfo;
    }
    
    public void setSimInfo(SimInfo simInfo) {
        this.simInfo = simInfo;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public Date getDateAffect() {
        return this.dateAffect;
    }
    
    public void setDateAffect(Date dateAffect) {
        this.dateAffect = dateAffect;
    }
    public Date getDateDeactivation() {
        return this.dateDeactivation;
    }
    
    public void setDateDeactivation(Date dateDeactivation) {
        this.dateDeactivation = dateDeactivation;
    }
    public Double getLimitTransact() {
        return this.limitTransact;
    }
    
    public void setLimitTransact(Double limitTransact) {
        this.limitTransact = limitTransact;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set<TransactionTopup> getTransactionTopups() {
        return this.transactionTopups;
    }
    
    public void setTransactionTopups(Set<TransactionTopup> transactionTopups) {
        this.transactionTopups = transactionTopups;
    }




}


