package model_db;


import java.util.HashSet;
import java.util.Set;

/**
 * SimType generated by hbm2java
 */
public class SimType  implements java.io.Serializable {


     private Integer idsimType;
     private String simTypeDesc;
     private Integer flag;
     private Set simInfos = new HashSet(0);

    public SimType() {
    }

	
    public SimType(String simTypeDesc) {
        this.simTypeDesc = simTypeDesc;
    }
    public SimType(String simTypeDesc, Integer flag, Set simInfos) {
       this.simTypeDesc = simTypeDesc;
       this.flag = flag;
       this.simInfos = simInfos;
    }
   
    public Integer getIdsimType() {
        return this.idsimType;
    }
    
    public void setIdsimType(Integer idsimType) {
        this.idsimType = idsimType;
    }
    public String getSimTypeDesc() {
        return this.simTypeDesc;
    }
    
    public void setSimTypeDesc(String simTypeDesc) {
        this.simTypeDesc = simTypeDesc;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set getSimInfos() {
        return this.simInfos;
    }
    
    public void setSimInfos(Set simInfos) {
        this.simInfos = simInfos;
    }




}


