package model_db;
// Generated Jun 27, 2020 1:59:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * StationType generated by hbm2java
 */
public class StationType  implements java.io.Serializable {


     private Integer idstationType;
     private String stationTypeDesc;
     private Integer flag;
     private Set<Station> stations = new HashSet<Station>(0);

    public StationType() {
    }

	
    public StationType(String stationTypeDesc) {
        this.stationTypeDesc = stationTypeDesc;
    }
    public StationType(String stationTypeDesc, Integer flag, Set<Station> stations) {
       this.stationTypeDesc = stationTypeDesc;
       this.flag = flag;
       this.stations = stations;
    }
   
    public Integer getIdstationType() {
        return this.idstationType;
    }
    
    public void setIdstationType(Integer idstationType) {
        this.idstationType = idstationType;
    }
    public String getStationTypeDesc() {
        return this.stationTypeDesc;
    }
    
    public void setStationTypeDesc(String stationTypeDesc) {
        this.stationTypeDesc = stationTypeDesc;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set<Station> getStations() {
        return this.stations;
    }
    
    public void setStations(Set<Station> stations) {
        this.stations = stations;
    }




}


