package model_db;


import java.util.HashSet;
import java.util.Set;

/**
 * StatusInfo generated by hbm2java
 */
public class StatusInfo  implements java.io.Serializable {


     private Integer idstatusInfo;
     private String statusInfoDesc;
     private Integer flag;
     private Set stations = new HashSet(0);
     private Set simInfos = new HashSet(0);
     private Set portInfos = new HashSet(0);
     private Set traders = new HashSet(0);
     private Set transactionSoldes = new HashSet(0);
     private Set transactionTopups = new HashSet(0);

    public StatusInfo() {
    }

	
    public StatusInfo(String statusInfoDesc) {
        this.statusInfoDesc = statusInfoDesc;
    }
    public StatusInfo(String statusInfoDesc, Integer flag, Set stations, Set simInfos, Set portInfos, Set traders, Set transactionSoldes, Set transactionTopups) {
       this.statusInfoDesc = statusInfoDesc;
       this.flag = flag;
       this.stations = stations;
       this.simInfos = simInfos;
       this.portInfos = portInfos;
       this.traders = traders;
       this.transactionSoldes = transactionSoldes;
       this.transactionTopups = transactionTopups;
    }
   
    public Integer getIdstatusInfo() {
        return this.idstatusInfo;
    }
    
    public void setIdstatusInfo(Integer idstatusInfo) {
        this.idstatusInfo = idstatusInfo;
    }
    public String getStatusInfoDesc() {
        return this.statusInfoDesc;
    }
    
    public void setStatusInfoDesc(String statusInfoDesc) {
        this.statusInfoDesc = statusInfoDesc;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set getStations() {
        return this.stations;
    }
    
    public void setStations(Set stations) {
        this.stations = stations;
    }
    public Set getSimInfos() {
        return this.simInfos;
    }
    
    public void setSimInfos(Set simInfos) {
        this.simInfos = simInfos;
    }
    public Set getPortInfos() {
        return this.portInfos;
    }
    
    public void setPortInfos(Set portInfos) {
        this.portInfos = portInfos;
    }
    public Set getTraders() {
        return this.traders;
    }
    
    public void setTraders(Set traders) {
        this.traders = traders;
    }
    public Set getTransactionSoldes() {
        return this.transactionSoldes;
    }
    
    public void setTransactionSoldes(Set transactionSoldes) {
        this.transactionSoldes = transactionSoldes;
    }
    public Set getTransactionTopups() {
        return this.transactionTopups;
    }
    
    public void setTransactionTopups(Set transactionTopups) {
        this.transactionTopups = transactionTopups;
    }




}


