package model_db;
// Generated Jun 27, 2020 1:59:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Station generated by hbm2java
 */
public class Station  implements java.io.Serializable {


     private Integer idstation;
     private ServerProfile serverProfile;
     private StationType stationType;
     private StatusInfo statusInfo;
     private Trader trader;
     private UserInfo userInfo;
     private String stationBrand;
     private String stationReference;
     private String stationSn1;
     private String stationSn2;
     private String appversion;
     private Integer flag;
     private Set<TransactionTopup> transactionTopups = new HashSet<TransactionTopup>(0);
     private Set<StationLoginSession> stationLoginSessions = new HashSet<StationLoginSession>(0);

    public Station() {
    }

	
    public Station(StationType stationType, StatusInfo statusInfo, Trader trader, UserInfo userInfo, String stationBrand, String stationReference, String stationSn1, String stationSn2, String appversion) {
        this.stationType = stationType;
        this.statusInfo = statusInfo;
        this.trader = trader;
        this.userInfo = userInfo;
        this.stationBrand = stationBrand;
        this.stationReference = stationReference;
        this.stationSn1 = stationSn1;
        this.stationSn2 = stationSn2;
        this.appversion = appversion;
    }
    public Station(ServerProfile serverProfile, StationType stationType, StatusInfo statusInfo, Trader trader, UserInfo userInfo, String stationBrand, String stationReference, String stationSn1, String stationSn2, String appversion, Integer flag, Set<TransactionTopup> transactionTopups, Set<StationLoginSession> stationLoginSessions) {
       this.serverProfile = serverProfile;
       this.stationType = stationType;
       this.statusInfo = statusInfo;
       this.trader = trader;
       this.userInfo = userInfo;
       this.stationBrand = stationBrand;
       this.stationReference = stationReference;
       this.stationSn1 = stationSn1;
       this.stationSn2 = stationSn2;
       this.appversion = appversion;
       this.flag = flag;
       this.transactionTopups = transactionTopups;
       this.stationLoginSessions = stationLoginSessions;
    }
   
    public Integer getIdstation() {
        return this.idstation;
    }
    
    public void setIdstation(Integer idstation) {
        this.idstation = idstation;
    }
    public ServerProfile getServerProfile() {
        return this.serverProfile;
    }
    
    public void setServerProfile(ServerProfile serverProfile) {
        this.serverProfile = serverProfile;
    }
    public StationType getStationType() {
        return this.stationType;
    }
    
    public void setStationType(StationType stationType) {
        this.stationType = stationType;
    }
    public StatusInfo getStatusInfo() {
        return this.statusInfo;
    }
    
    public void setStatusInfo(StatusInfo statusInfo) {
        this.statusInfo = statusInfo;
    }
    public Trader getTrader() {
        return this.trader;
    }
    
    public void setTrader(Trader trader) {
        this.trader = trader;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public String getStationBrand() {
        return this.stationBrand;
    }
    
    public void setStationBrand(String stationBrand) {
        this.stationBrand = stationBrand;
    }
    public String getStationReference() {
        return this.stationReference;
    }
    
    public void setStationReference(String stationReference) {
        this.stationReference = stationReference;
    }
    public String getStationSn1() {
        return this.stationSn1;
    }
    
    public void setStationSn1(String stationSn1) {
        this.stationSn1 = stationSn1;
    }
    public String getStationSn2() {
        return this.stationSn2;
    }
    
    public void setStationSn2(String stationSn2) {
        this.stationSn2 = stationSn2;
    }
    public String getAppversion() {
        return this.appversion;
    }
    
    public void setAppversion(String appversion) {
        this.appversion = appversion;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set<TransactionTopup> getTransactionTopups() {
        return this.transactionTopups;
    }
    
    public void setTransactionTopups(Set<TransactionTopup> transactionTopups) {
        this.transactionTopups = transactionTopups;
    }
    public Set<StationLoginSession> getStationLoginSessions() {
        return this.stationLoginSessions;
    }
    
    public void setStationLoginSessions(Set<StationLoginSession> stationLoginSessions) {
        this.stationLoginSessions = stationLoginSessions;
    }




}


