package model_db;
// Generated Jun 27, 2020 1:59:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Trader generated by hbm2java
 */ 
public class Trader  implements java.io.Serializable {


     private Integer idtrader;
     private StatusInfo statusInfo;
     private TraderCategory traderCategory;
     private TraderType traderType;
     private UserInfo userInfoByIduserInfoUpdate;
     private UserInfo userInfoByIduserInfo;
     private String traderFname;
     private String traderLname;
     private String traderCompany;
     private String simnumber;
     private String adresse;
     private String commune;
     private String wilaya;
     private String email1;
     private String email2;
     private String tel1;
     private String tel2;
     private Integer flag;
     private Set<Station> stations = new HashSet<Station>(0);
     private Set<ProviderClient> providerClientsForIdclient = new HashSet<ProviderClient>(0);
     private Set<ProviderClient> providerClientsForIdprovider = new HashSet<ProviderClient>(0);
     private Set<UserInfo> userInfos = new HashSet<UserInfo>(0);

    public Trader() {
    }

	
    public Trader(StatusInfo statusInfo, TraderCategory traderCategory, TraderType traderType, UserInfo userInfoByIduserInfoUpdate, UserInfo userInfoByIduserInfo, String traderFname, String traderLname, String traderCompany, String simnumber, String adresse, String commune, String wilaya, String email1, String email2, String tel1, String tel2) {
        this.statusInfo = statusInfo;
        this.traderCategory = traderCategory;
        this.traderType = traderType;
        this.userInfoByIduserInfoUpdate = userInfoByIduserInfoUpdate;
        this.userInfoByIduserInfo = userInfoByIduserInfo;
        this.traderFname = traderFname;
        this.traderLname = traderLname;
        this.traderCompany = traderCompany;
        this.simnumber = simnumber;
        this.adresse = adresse;
        this.commune = commune;
        this.wilaya = wilaya;
        this.email1 = email1;
        this.email2 = email2;
        this.tel1 = tel1;
        this.tel2 = tel2;
    }
    public Trader(StatusInfo statusInfo, TraderCategory traderCategory, TraderType traderType, UserInfo userInfoByIduserInfoUpdate, UserInfo userInfoByIduserInfo, String traderFname, String traderLname, String traderCompany, String simnumber, String adresse, String commune, String wilaya, String email1, String email2, String tel1, String tel2, Integer flag, Set<Station> stations, Set<ProviderClient> providerClientsForIdclient, Set<ProviderClient> providerClientsForIdprovider, Set<UserInfo> userInfos) {
       this.statusInfo = statusInfo;
       this.traderCategory = traderCategory;
       this.traderType = traderType;
       this.userInfoByIduserInfoUpdate = userInfoByIduserInfoUpdate;
       this.userInfoByIduserInfo = userInfoByIduserInfo;
       this.traderFname = traderFname;
       this.traderLname = traderLname;
       this.traderCompany = traderCompany;
       this.simnumber = simnumber;
       this.adresse = adresse;
       this.commune = commune;
       this.wilaya = wilaya;
       this.email1 = email1;
       this.email2 = email2;
       this.tel1 = tel1;
       this.tel2 = tel2;
       this.flag = flag;
       this.stations = stations;
       this.providerClientsForIdclient = providerClientsForIdclient;
       this.providerClientsForIdprovider = providerClientsForIdprovider;
       this.userInfos = userInfos;
    }
   
    public Integer getIdtrader() {
        return this.idtrader;
    }
    
    public void setIdtrader(Integer idtrader) {
        this.idtrader = idtrader;
    }
    public StatusInfo getStatusInfo() {
        return this.statusInfo;
    }
    
    public void setStatusInfo(StatusInfo statusInfo) {
        this.statusInfo = statusInfo;
    }
    public TraderCategory getTraderCategory() {
        return this.traderCategory;
    }
    
    public void setTraderCategory(TraderCategory traderCategory) {
        this.traderCategory = traderCategory;
    }
    public TraderType getTraderType() {
        return this.traderType;
    }
    
    public void setTraderType(TraderType traderType) {
        this.traderType = traderType;
    }
    public UserInfo getUserInfoByIduserInfoUpdate() {
        return this.userInfoByIduserInfoUpdate;
    }
    
    public void setUserInfoByIduserInfoUpdate(UserInfo userInfoByIduserInfoUpdate) {
        this.userInfoByIduserInfoUpdate = userInfoByIduserInfoUpdate;
    }
    public UserInfo getUserInfoByIduserInfo() {
        return this.userInfoByIduserInfo;
    }
    
    public void setUserInfoByIduserInfo(UserInfo userInfoByIduserInfo) {
        this.userInfoByIduserInfo = userInfoByIduserInfo;
    }
    public String getTraderFname() {
        return this.traderFname;
    }
    
    public void setTraderFname(String traderFname) {
        this.traderFname = traderFname;
    }
    public String getTraderLname() {
        return this.traderLname;
    }
    
    public void setTraderLname(String traderLname) {
        this.traderLname = traderLname;
    }
    public String getTraderCompany() {
        return this.traderCompany;
    }
    
    public void setTraderCompany(String traderCompany) {
        this.traderCompany = traderCompany;
    }
    public String getSimnumber() {
        return this.simnumber;
    }
    
    public void setSimnumber(String simnumber) {
        this.simnumber = simnumber;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getCommune() {
        return this.commune;
    }
    
    public void setCommune(String commune) {
        this.commune = commune;
    }
    public String getWilaya() {
        return this.wilaya;
    }
    
    public void setWilaya(String wilaya) {
        this.wilaya = wilaya;
    }
    public String getEmail1() {
        return this.email1;
    }
    
    public void setEmail1(String email1) {
        this.email1 = email1;
    }
    public String getEmail2() {
        return this.email2;
    }
    
    public void setEmail2(String email2) {
        this.email2 = email2;
    }
    public String getTel1() {
        return this.tel1;
    }
    
    public void setTel1(String tel1) {
        this.tel1 = tel1;
    }
    public String getTel2() {
        return this.tel2;
    }
    
    public void setTel2(String tel2) {
        this.tel2 = tel2;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set<Station> getStations() {
        return this.stations;
    }
    
    public void setStations(Set<Station> stations) {
        this.stations = stations;
    }
    public Set<ProviderClient> getProviderClientsForIdclient() {
        return this.providerClientsForIdclient;
    }
    
    public void setProviderClientsForIdclient(Set<ProviderClient> providerClientsForIdclient) {
        this.providerClientsForIdclient = providerClientsForIdclient;
    }
    public Set<ProviderClient> getProviderClientsForIdprovider() {
        return this.providerClientsForIdprovider;
    }
    
    public void setProviderClientsForIdprovider(Set<ProviderClient> providerClientsForIdprovider) {
        this.providerClientsForIdprovider = providerClientsForIdprovider;
    }
    public Set<UserInfo> getUserInfos() {
        return this.userInfos;
    }
    
    public void setUserInfos(Set<UserInfo> userInfos) {
        this.userInfos = userInfos;
    }




}


