package model_db;

import java.util.HashSet;
import java.util.Set;

/**
 * TraderCategory generated by hbm2java
 */
public class TraderCategory  implements java.io.Serializable {


     private Integer idtraderCategory;
     private String traderCategoryDesc;
     private Integer flag;
     private Set traders = new HashSet(0);

    public TraderCategory() {
    }

	
    public TraderCategory(String traderCategoryDesc) {
        this.traderCategoryDesc = traderCategoryDesc;
    }
    public TraderCategory(String traderCategoryDesc, Integer flag, Set traders) {
       this.traderCategoryDesc = traderCategoryDesc;
       this.flag = flag;
       this.traders = traders;
    }
   
    public Integer getIdtraderCategory() {
        return this.idtraderCategory;
    }
    
    public void setIdtraderCategory(Integer idtraderCategory) {
        this.idtraderCategory = idtraderCategory;
    }
    public String getTraderCategoryDesc() {
        return this.traderCategoryDesc;
    }
    
    public void setTraderCategoryDesc(String traderCategoryDesc) {
        this.traderCategoryDesc = traderCategoryDesc;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set getTraders() {
        return this.traders;
    }
    
    public void setTraders(Set traders) {
        this.traders = traders;
    }




}


