package model_db;


import java.util.HashSet;
import java.util.Set;

/**
 * TraderType generated by hbm2java
 */
public class TraderType  implements java.io.Serializable {


     private Integer idtraderType;
     private String traderTypeDesc;
     private Integer flag;
     private Set traders = new HashSet(0);

    public TraderType() {
    }

	
    public TraderType(String traderTypeDesc) {
        this.traderTypeDesc = traderTypeDesc;
    }
    public TraderType(String traderTypeDesc, Integer flag, Set traders) {
       this.traderTypeDesc = traderTypeDesc;
       this.flag = flag;
       this.traders = traders;
    }
   
    public Integer getIdtraderType() {
        return this.idtraderType;
    }
    
    public void setIdtraderType(Integer idtraderType) {
        this.idtraderType = idtraderType;
    }
    public String getTraderTypeDesc() {
        return this.traderTypeDesc;
    }
    
    public void setTraderTypeDesc(String traderTypeDesc) {
        this.traderTypeDesc = traderTypeDesc;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set getTraders() {
        return this.traders;
    }
    
    public void setTraders(Set traders) {
        this.traders = traders;
    }




}


