package model_db;


import java.util.HashSet;
import java.util.Set;

/**
 * TransactionType generated by hbm2java
 */
public class TransactionType  implements java.io.Serializable {


     private Integer idtransactionType;
     private String transactionTypeDesc;
     private Integer flag;
     private Set transactionTopups = new HashSet(0);

    public TransactionType() {
    }

	
    public TransactionType(String transactionTypeDesc) {
        this.transactionTypeDesc = transactionTypeDesc;
    }
    public TransactionType(String transactionTypeDesc, Integer flag, Set transactionTopups) {
       this.transactionTypeDesc = transactionTypeDesc;
       this.flag = flag;
       this.transactionTopups = transactionTopups;
    }
   
    public Integer getIdtransactionType() {
        return this.idtransactionType;
    }
    
    public void setIdtransactionType(Integer idtransactionType) {
        this.idtransactionType = idtransactionType;
    }
    public String getTransactionTypeDesc() {
        return this.transactionTypeDesc;
    }
    
    public void setTransactionTypeDesc(String transactionTypeDesc) {
        this.transactionTypeDesc = transactionTypeDesc;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set getTransactionTopups() {
        return this.transactionTopups;
    }
    
    public void setTransactionTopups(Set transactionTopups) {
        this.transactionTopups = transactionTopups;
    }




}


