package model_db;
// Generated Jun 27, 2020 1:59:00 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TransactionTopup generated by hbm2java
 */
public class TransactionTopup  implements java.io.Serializable {


     private Integer idtransacttopup;
     private ProviderClient providerClient;
     private SimOffer simOffer;
     private Station station;
     private StatusInfo statusInfo;
     private TransactionType transactionType;
     private UserInfo userInfo;
     private String simClient;
     private String transactToken;
     private double newSolde;
     private double transactAmount;
     private double realTransactAmount;
     private Date transactDate;
     private double transactDuration;
     private String recievedMessage;
     private String sentMessage;
     private Integer flag;

    public TransactionTopup() {
    }

	
    public TransactionTopup(StatusInfo statusInfo, TransactionType transactionType, String simClient, double newSolde, double transactAmount, double realTransactAmount, Date transactDate, double transactDuration, String recievedMessage, String sentMessage) {
        this.statusInfo = statusInfo;
        this.transactionType = transactionType;
        this.simClient = simClient;
        this.newSolde = newSolde;
        this.transactAmount = transactAmount;
        this.realTransactAmount = realTransactAmount;
        this.transactDate = transactDate;
        this.transactDuration = transactDuration;
        this.recievedMessage = recievedMessage;
        this.sentMessage = sentMessage;
    }
    public TransactionTopup(ProviderClient providerClient, SimOffer simOffer, Station station, StatusInfo statusInfo, TransactionType transactionType, UserInfo userInfo, String simClient, String transactToken, double newSolde, double transactAmount, double realTransactAmount, Date transactDate, double transactDuration, String recievedMessage, String sentMessage, Integer flag) {
       this.providerClient = providerClient;
       this.simOffer = simOffer;
       this.station = station;
       this.statusInfo = statusInfo;
       this.transactionType = transactionType;
       this.userInfo = userInfo;
       this.simClient = simClient;
       this.transactToken = transactToken;
       this.newSolde = newSolde;
       this.transactAmount = transactAmount;
       this.realTransactAmount = realTransactAmount;
       this.transactDate = transactDate;
       this.transactDuration = transactDuration;
       this.recievedMessage = recievedMessage;
       this.sentMessage = sentMessage;
       this.flag = flag;
    }
   
    public Integer getIdtransacttopup() {
        return this.idtransacttopup;
    }
    
    public void setIdtransacttopup(Integer idtransacttopup) {
        this.idtransacttopup = idtransacttopup;
    }
    public ProviderClient getProviderClient() {
        return this.providerClient;
    }
    
    public void setProviderClient(ProviderClient providerClient) {
        this.providerClient = providerClient;
    }
    public SimOffer getSimOffer() {
        return this.simOffer;
    }
    
    public void setSimOffer(SimOffer simOffer) {
        this.simOffer = simOffer;
    }
    public Station getStation() {
        return this.station;
    }
    
    public void setStation(Station station) {
        this.station = station;
    }
    public StatusInfo getStatusInfo() {
        return this.statusInfo;
    }
    
    public void setStatusInfo(StatusInfo statusInfo) {
        this.statusInfo = statusInfo;
    }
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public String getSimClient() {
        return this.simClient;
    }
    
    public void setSimClient(String simClient) {
        this.simClient = simClient;
    }
    public String getTransactToken() {
        return this.transactToken;
    }
    
    public void setTransactToken(String transactToken) {
        this.transactToken = transactToken;
    }
    public double getNewSolde() {
        return this.newSolde;
    }
    
    public void setNewSolde(double newSolde) {
        this.newSolde = newSolde;
    }
    public double getTransactAmount() {
        return this.transactAmount;
    }
    
    public void setTransactAmount(double transactAmount) {
        this.transactAmount = transactAmount;
    }
    public double getRealTransactAmount() {
        return this.realTransactAmount;
    }
    
    public void setRealTransactAmount(double realTransactAmount) {
        this.realTransactAmount = realTransactAmount;
    }
    public Date getTransactDate() {
        return this.transactDate;
    }
    
    public void setTransactDate(Date transactDate) {
        this.transactDate = transactDate;
    }
    public double getTransactDuration() {
        return this.transactDuration;
    }
    
    public void setTransactDuration(double transactDuration) {
        this.transactDuration = transactDuration;
    }
    public String getRecievedMessage() {
        return this.recievedMessage;
    }
    
    public void setRecievedMessage(String recievedMessage) {
        this.recievedMessage = recievedMessage;
    }
    public String getSentMessage() {
        return this.sentMessage;
    }
    
    public void setSentMessage(String sentMessage) {
        this.sentMessage = sentMessage;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }




}


