package model_db;
// Generated Jun 27, 2020 1:59:00 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TransactionSolde generated by hbm2java
 */
public class TransactionSolde  implements java.io.Serializable {


     private Integer idtransactsolde;
     private ProviderClient providerClient;
     private StatusInfo statusInfo;
     private UserInfo userInfo;
     private double oldSolde;
     private double newSolde;
     private double transactAmount;
     private Date transactDate;
     private Integer flag;

    public TransactionSolde() {
    }

	
    public TransactionSolde(ProviderClient providerClient, StatusInfo statusInfo, UserInfo userInfo, double oldSolde, double newSolde, double transactAmount, Date transactDate) {
        this.providerClient = providerClient;
        this.statusInfo = statusInfo;
        this.userInfo = userInfo;
        this.oldSolde = oldSolde;
        this.newSolde = newSolde;
        this.transactAmount = transactAmount;
        this.transactDate = transactDate;
    }
    public TransactionSolde(ProviderClient providerClient, StatusInfo statusInfo, UserInfo userInfo, double oldSolde, double newSolde, double transactAmount, Date transactDate, Integer flag) {
       this.providerClient = providerClient;
       this.statusInfo = statusInfo;
       this.userInfo = userInfo;
       this.oldSolde = oldSolde;
       this.newSolde = newSolde;
       this.transactAmount = transactAmount;
       this.transactDate = transactDate;
       this.flag = flag;
    }
   
    public Integer getIdtransactsolde() {
        return this.idtransactsolde;
    }
    
    public void setIdtransactsolde(Integer idtransactsolde) {
        this.idtransactsolde = idtransactsolde;
    }
    public ProviderClient getProviderClient() {
        return this.providerClient;
    }
    
    public void setProviderClient(ProviderClient providerClient) {
        this.providerClient = providerClient;
    }
    public StatusInfo getStatusInfo() {
        return this.statusInfo;
    }
    
    public void setStatusInfo(StatusInfo statusInfo) {
        this.statusInfo = statusInfo;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public double getOldSolde() {
        return this.oldSolde;
    }
    
    public void setOldSolde(double oldSolde) {
        this.oldSolde = oldSolde;
    }
    public double getNewSolde() {
        return this.newSolde;
    }
    
    public void setNewSolde(double newSolde) {
        this.newSolde = newSolde;
    }
    public double getTransactAmount() {
        return this.transactAmount;
    }
    
    public void setTransactAmount(double transactAmount) {
        this.transactAmount = transactAmount;
    }
    public Date getTransactDate() {
        return this.transactDate;
    }
    
    public void setTransactDate(Date transactDate) {
        this.transactDate = transactDate;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }




}


