package model_db;
// Generated Jun 27, 2020 1:59:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo  implements java.io.Serializable {


     private Integer iduserInfo;
     private Trader trader;
     private UserCategory userCategory;
     private UserInfo userInfo;
     private String username;
     private String password;
     private Integer flag;
     private Set<SimOffer> simOffers = new HashSet<SimOffer>(0);
     private Set<Trader> tradersForIduserInfoUpdate = new HashSet<Trader>(0);
     private Set<Trader> tradersForIduserInfo = new HashSet<Trader>(0);
     private Set<ServerProfile> serverProfiles = new HashSet<ServerProfile>(0);
     private Set<Station> stations = new HashSet<Station>(0);
     private Set<OfferInfo> offerInfosForIduserInfo = new HashSet<OfferInfo>(0);
     private Set<TransactionSolde> transactionSoldes = new HashSet<TransactionSolde>(0);
     private Set<UserInfo> userInfos = new HashSet<UserInfo>(0);
     private Set<ProviderClient> providerClients = new HashSet<ProviderClient>(0);
     private Set<OfferInfo> offerInfosForIduserInfoUpdate = new HashSet<OfferInfo>(0);
     private Set<TransactionTopup> transactionTopups = new HashSet<TransactionTopup>(0);

    public UserInfo() {
    }

	
    public UserInfo(UserCategory userCategory, String username, String password) {
        this.userCategory = userCategory;
        this.username = username;
        this.password = password;
    }
    public UserInfo(Trader trader, UserCategory userCategory, UserInfo userInfo, String username, String password, Integer flag, Set<SimOffer> simOffers, Set<Trader> tradersForIduserInfoUpdate, Set<Trader> tradersForIduserInfo, Set<ServerProfile> serverProfiles, Set<Station> stations, Set<OfferInfo> offerInfosForIduserInfo, Set<TransactionSolde> transactionSoldes, Set<UserInfo> userInfos, Set<ProviderClient> providerClients, Set<OfferInfo> offerInfosForIduserInfoUpdate, Set<TransactionTopup> transactionTopups) {
       this.trader = trader;
       this.userCategory = userCategory;
       this.userInfo = userInfo;
       this.username = username;
       this.password = password;
       this.flag = flag;
       this.simOffers = simOffers;
       this.tradersForIduserInfoUpdate = tradersForIduserInfoUpdate;
       this.tradersForIduserInfo = tradersForIduserInfo;
       this.serverProfiles = serverProfiles;
       this.stations = stations;
       this.offerInfosForIduserInfo = offerInfosForIduserInfo;
       this.transactionSoldes = transactionSoldes;
       this.userInfos = userInfos;
       this.providerClients = providerClients;
       this.offerInfosForIduserInfoUpdate = offerInfosForIduserInfoUpdate;
       this.transactionTopups = transactionTopups;
    }
   
    public Integer getIduserInfo() {
        return this.iduserInfo;
    }
    
    public void setIduserInfo(Integer iduserInfo) {
        this.iduserInfo = iduserInfo;
    }
    public Trader getTrader() {
        return this.trader;
    }
    
    public void setTrader(Trader trader) {
        this.trader = trader;
    }
    public UserCategory getUserCategory() {
        return this.userCategory;
    }
    
    public void setUserCategory(UserCategory userCategory) {
        this.userCategory = userCategory;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set<SimOffer> getSimOffers() {
        return this.simOffers;
    }
    
    public void setSimOffers(Set<SimOffer> simOffers) {
        this.simOffers = simOffers;
    }
    public Set<Trader> getTradersForIduserInfoUpdate() {
        return this.tradersForIduserInfoUpdate;
    }
    
    public void setTradersForIduserInfoUpdate(Set<Trader> tradersForIduserInfoUpdate) {
        this.tradersForIduserInfoUpdate = tradersForIduserInfoUpdate;
    }
    public Set<Trader> getTradersForIduserInfo() {
        return this.tradersForIduserInfo;
    }
    
    public void setTradersForIduserInfo(Set<Trader> tradersForIduserInfo) {
        this.tradersForIduserInfo = tradersForIduserInfo;
    }
    public Set<ServerProfile> getServerProfiles() {
        return this.serverProfiles;
    }
    
    public void setServerProfiles(Set<ServerProfile> serverProfiles) {
        this.serverProfiles = serverProfiles;
    }
    public Set<Station> getStations() {
        return this.stations;
    }
    
    public void setStations(Set<Station> stations) {
        this.stations = stations;
    }
    public Set<OfferInfo> getOfferInfosForIduserInfo() {
        return this.offerInfosForIduserInfo;
    }
    
    public void setOfferInfosForIduserInfo(Set<OfferInfo> offerInfosForIduserInfo) {
        this.offerInfosForIduserInfo = offerInfosForIduserInfo;
    }
    public Set<TransactionSolde> getTransactionSoldes() {
        return this.transactionSoldes;
    }
    
    public void setTransactionSoldes(Set<TransactionSolde> transactionSoldes) {
        this.transactionSoldes = transactionSoldes;
    }
    public Set<UserInfo> getUserInfos() {
        return this.userInfos;
    }
    
    public void setUserInfos(Set<UserInfo> userInfos) {
        this.userInfos = userInfos;
    }
    public Set<ProviderClient> getProviderClients() {
        return this.providerClients;
    }
    
    public void setProviderClients(Set<ProviderClient> providerClients) {
        this.providerClients = providerClients;
    }
    public Set<OfferInfo> getOfferInfosForIduserInfoUpdate() {
        return this.offerInfosForIduserInfoUpdate;
    }
    
    public void setOfferInfosForIduserInfoUpdate(Set<OfferInfo> offerInfosForIduserInfoUpdate) {
        this.offerInfosForIduserInfoUpdate = offerInfosForIduserInfoUpdate;
    }
    public Set<TransactionTopup> getTransactionTopups() {
        return this.transactionTopups;
    }
    
    public void setTransactionTopups(Set<TransactionTopup> transactionTopups) {
        this.transactionTopups = transactionTopups;
    }




}


