package model_db;


import java.util.HashSet;
import java.util.Set;

/**
 * UserCategory generated by hbm2java
 */
public class UserCategory  implements java.io.Serializable {


     private Integer iduserCategory;
     private String userCategoryDesc;
     private Integer flag;
     private Set userInfos = new HashSet(0);

    public UserCategory() {
    }

	
    public UserCategory(String userCategoryDesc) {
        this.userCategoryDesc = userCategoryDesc;
    }
    public UserCategory(String userCategoryDesc, Integer flag, Set userInfos) {
       this.userCategoryDesc = userCategoryDesc;
       this.flag = flag;
       this.userInfos = userInfos;
    }
   
    public Integer getIduserCategory() {
        return this.iduserCategory;
    }
    
    public void setIduserCategory(Integer iduserCategory) {
        this.iduserCategory = iduserCategory;
    }
    public String getUserCategoryDesc() {
        return this.userCategoryDesc;
    }
    
    public void setUserCategoryDesc(String userCategoryDesc) {
        this.userCategoryDesc = userCategoryDesc;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set getUserInfos() {
        return this.userInfos;
    }
    
    public void setUserInfos(Set userInfos) {
        this.userInfos = userInfos;
    }




}


