package model_db;


import java.util.HashSet;
import java.util.Set;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo  implements java.io.Serializable {


     private Integer iduserInfo;
     private Trader trader;
     private UserCategory userCategory;
     private UserInfo userInfo;
     private String username;
     private String password;
     private Integer flag;
     private Set simOffers = new HashSet(0);
     private Set tradersForIduserInfoUpdate = new HashSet(0);
     private Set tradersForIduserInfo = new HashSet(0);
     private Set stations = new HashSet(0);
     private Set offerInfosForIduserInfo = new HashSet(0);
     private Set transactionSoldes = new HashSet(0);
     private Set userInfos = new HashSet(0);
     private Set providerClients = new HashSet(0);
     private Set offerInfosForIduserInfoUpdate = new HashSet(0);
     private Set transactionTopups = new HashSet(0);

    public UserInfo() {
    }

	
    public UserInfo(UserCategory userCategory, String username, String password) {
        this.userCategory = userCategory;
        this.username = username;
        this.password = password;
    }
    public UserInfo(Trader trader, UserCategory userCategory, UserInfo userInfo, String username, String password, Integer flag, Set simOffers, Set tradersForIduserInfoUpdate, Set tradersForIduserInfo, Set stations, Set offerInfosForIduserInfo, Set transactionSoldes, Set userInfos, Set providerClients, Set offerInfosForIduserInfoUpdate, Set transactionTopups) {
       this.trader = trader;
       this.userCategory = userCategory;
       this.userInfo = userInfo;
       this.username = username;
       this.password = password;
       this.flag = flag;
       this.simOffers = simOffers;
       this.tradersForIduserInfoUpdate = tradersForIduserInfoUpdate;
       this.tradersForIduserInfo = tradersForIduserInfo;
       this.stations = stations;
       this.offerInfosForIduserInfo = offerInfosForIduserInfo;
       this.transactionSoldes = transactionSoldes;
       this.userInfos = userInfos;
       this.providerClients = providerClients;
       this.offerInfosForIduserInfoUpdate = offerInfosForIduserInfoUpdate;
       this.transactionTopups = transactionTopups;
    }
   
    public Integer getIduserInfo() {
        return this.iduserInfo;
    }
    
    public void setIduserInfo(Integer iduserInfo) {
        this.iduserInfo = iduserInfo;
    }
    public Trader getTrader() {
        return this.trader;
    }
    
    public void setTrader(Trader trader) {
        this.trader = trader;
    }
    public UserCategory getUserCategory() {
        return this.userCategory;
    }
    
    public void setUserCategory(UserCategory userCategory) {
        this.userCategory = userCategory;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
    public Set getSimOffers() {
        return this.simOffers;
    }
    
    public void setSimOffers(Set simOffers) {
        this.simOffers = simOffers;
    }
    public Set getTradersForIduserInfoUpdate() {
        return this.tradersForIduserInfoUpdate;
    }
    
    public void setTradersForIduserInfoUpdate(Set tradersForIduserInfoUpdate) {
        this.tradersForIduserInfoUpdate = tradersForIduserInfoUpdate;
    }
    public Set getTradersForIduserInfo() {
        return this.tradersForIduserInfo;
    }
    
    public void setTradersForIduserInfo(Set tradersForIduserInfo) {
        this.tradersForIduserInfo = tradersForIduserInfo;
    }
    public Set getStations() {
        return this.stations;
    }
    
    public void setStations(Set stations) {
        this.stations = stations;
    }
    public Set getOfferInfosForIduserInfo() {
        return this.offerInfosForIduserInfo;
    }
    
    public void setOfferInfosForIduserInfo(Set offerInfosForIduserInfo) {
        this.offerInfosForIduserInfo = offerInfosForIduserInfo;
    }
    public Set getTransactionSoldes() {
        return this.transactionSoldes;
    }
    
    public void setTransactionSoldes(Set transactionSoldes) {
        this.transactionSoldes = transactionSoldes;
    }
    public Set getUserInfos() {
        return this.userInfos;
    }
    
    public void setUserInfos(Set userInfos) {
        this.userInfos = userInfos;
    }
    public Set getProviderClients() {
        return this.providerClients;
    }
    
    public void setProviderClients(Set providerClients) {
        this.providerClients = providerClients;
    }
    public Set getOfferInfosForIduserInfoUpdate() {
        return this.offerInfosForIduserInfoUpdate;
    }
    
    public void setOfferInfosForIduserInfoUpdate(Set offerInfosForIduserInfoUpdate) {
        this.offerInfosForIduserInfoUpdate = offerInfosForIduserInfoUpdate;
    }
    public Set getTransactionTopups() {
        return this.transactionTopups;
    }
    
    public void setTransactionTopups(Set transactionTopups) {
        this.transactionTopups = transactionTopups;
    }




}


