package model_helpers;

import java.util.List;
import model_db.OfferInfo;
import model_db.OfferInfoDetails;
import model_db.OfferType;
import model_db.Operator;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;


/**
 * OfferInfo generated by hbm2java
 */
public class OfferInfoDetails_Util {

    public List getAllOfferInfo(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferInfoDetails where flag=0", suffix);

    }

    public OfferInfoDetails getOfferInfo_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferInfoDetails where flag=0 and idofferInfoDetails = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((OfferInfoDetails) list.get(0));
        }
    }

    public List getOfferInfoDetails_by_offerInfo(Session session, OfferInfo offer, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferInfoDetails where flag=0 and offerInfo = " + offer.getIdofferInfo(), suffix);

    }
    
    public List getOfferInfoDetails_by_columnDescLike(Session session, String offerDesc, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferInfoDetails where flag=0 and columnDesc LIKE '%" + offerDesc + "%'", suffix);
    }
    
    public List getOfferInfoDetails_by_columnDesc(Session session, String offerDesc, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferInfoDetails where flag=0 and columnDesc = '" + offerDesc + "'", suffix);
    }

    public void addOfferInfoDetails(OfferInfoDetails adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updateOfferInfoDetails(OfferInfoDetails adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }

}
