package model_helpers;

import java.util.List;
import model_db.OfferType;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;

/**
 * OfferType generated by hbm2java
 */
public class OfferType_Util {

    public List getAllOfferType(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferType where flag=0", suffix);

    }

    public OfferType getOfferType_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferType where flag=0 and idofferType = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((OfferType) list.get(0));
        }
    }

    public List getOfferType_by_offerTypeDesc_Like(Session session, String offerDesc, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferType where flag=0 and offerTypeDesc LIKE '%" + offerDesc + "%'", suffix);
    }
    
    public OfferType getOfferType_by_offerTypeDesc(Session session, String offerDesc, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferType where flag=0 and offerTypeDesc = '" + offerDesc + "'", suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((OfferType) list.get(0));
        }
    }

    public void addOfferInfo(OfferType adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updateOfferInfo(OfferType adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }

}
