package model_helpers;

import java.util.List;
import model_db.OfferInfo;
import model_db.OfferType;
import model_db.Operator;
import model_util.HibernateUtil;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;

/**
 * OfferInfo generated by hbm2java
 */
public class OfferInfo_Util {

    public List getAllOfferInfo(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferInfo where flag=0", suffix);

    }

    public List getAllOfferInfo(String suffix) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferInfo where flag=0", suffix);

    }

    public OfferInfo getOfferInfo_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferInfo where flag=0 and idofferInfo = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((OfferInfo) list.get(0));
        }
    }

    public List getOfferInfo_by_operator(Session session, Operator operator, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferInfo where flag=0 and operator = " + operator.getIdoperator(), suffix);

    }

    public List getOfferInfo_by_offerType(Session session, OfferType offerType, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferInfo where flag=0 and offerType = " + offerType.getIdofferType(), suffix);

    }

    public List getOfferInfo_by_offerDesc(Session session, String offerDesc, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM OfferInfo where flag=0 and offerDesc LIKE '%" + offerDesc + "%'", suffix);
    }

    public void addOfferInfo(OfferInfo adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updateOfferInfo(OfferInfo adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }

}
