package model_helpers;

import java.util.List;
import model_db.Operator;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;

/**
 * Operator generated by hbm2java
 */
public class Operator_Util {

    public List getAllOperator(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Operator where flag=0", suffix);

    }

    public Operator getOperator_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Operator where flag=0 and idoperator = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((Operator) list.get(0));
        }
    }

    public List getOperator_by_operatorDesc(Session session, String operatorDesc, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Operator where flag=0 and operatorDesc = '" + operatorDesc + "'", suffix);
    }
    
    public List getOperator_by_operatorDesc_Like(Session session, String operatorDesc, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Operator where flag=0 and operatorDesc LIKE '%" + operatorDesc + "%'", suffix);
    }

    public void addOperator(Operator adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updateOperator(Operator adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }

}
