package model_helpers;

import java.util.List;
import model_db.PortInfo;
import model_db.StatusInfo;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;

/**
 * PortInfo generated by hbm2java
 */
public class PortInfo_Util {

    public List getAllPortInfo(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM PortInfo where flag=0", suffix);

    }

    public PortInfo getPortInfo_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM PortInfo where flag=0 and idportInfo = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((PortInfo) list.get(0));
        }
    }

    public List getPortInfo_by_operator(Session session, StatusInfo statusInfo, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM PortInfo where flag=0 and statusInfo = " + statusInfo.getIdstatusInfo(), suffix);

    }

    public List getPortInfo_by_portDesc(Session session, String portDesc, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM PortInfo where flag=0 and portDesc LIKE '%" + portDesc + "%'", suffix);
    }

    public List getPortInfo_by_score(Session session, double score1, double score2, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM PortInfo where flag=0 "
                + "and (score >= " + score1 + " and score <= " + score2 + ")",
                suffix);
    }

    public void addPortInfo(PortInfo adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updatePortInfo(PortInfo adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }

}
