package model_helpers;

import java.util.List;
import model_db.ServerProfile;
import model_db.StationType;
import model_util.HibernateUtil;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;


/**
 * SimType generated by hbm2java
 */
public class ServerProfile_Util {

    public List getAllServerProfile(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM ServerProfile where flag=0", suffix);

    }
  public List getAllServerProfile( String suffix) {
           Session session =    HibernateUtil.getSessionFactory().openSession();
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM ServerProfile where flag=0", suffix);

    }
  public ServerProfile getStationType_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM ServerProfile where flag=0 and idProfile = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((ServerProfile) list.get(0));
        }
    }
}


