package model_helpers;

import java.util.List;
import model_db.SimType;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;


/**
 * SimType generated by hbm2java
 */
public class SimType_Util {

    public List getAllSimType(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM SimType where flag=0", suffix);

    }

    public SimType getOfferType_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM SimType where flag=0 and idsimType = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((SimType) list.get(0));
        }
    }

    public List getSimType_by_simTypeDesc_Like(Session session, String offerDesc, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM SimType where flag=0 and simTypeDesc LIKE '%" + offerDesc + "%'", suffix);
    }
    
    public SimType getSimType_by_offerTypeDesc(Session session, String offerDesc, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM SimType where flag=0 and simTypeDesc = '" + offerDesc + "'", suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((SimType) list.get(0));
        }
    }

    public void addOfferInfo(SimType adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updateOfferInfo(SimType adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }


}


