package model_helpers;

import java.util.List;
import model_db.Station;
import model_db.StationType;
import model_db.StatusInfo;
import model_db.Trader;
import model_util.HibernateUtil;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;

/**
 * UserInfo generated by hbm2java
 */
public class station_Util {

    public List getAllStation(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Station where flag=0", suffix);

    }

     public List getAllStation( String suffix) {
                 Session session  =  HibernateUtil.getSessionFactory().openSession();

        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Station where flag=0", suffix);

    }
     
       public List getAllStationByTraderCategory( String category,String suffix) {
                 Session session  =  HibernateUtil.getSessionFactory().openSession();

        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Station where flag=0 and trader.traderCategory.traderCategoryDesc like '%"+category+"%'", suffix);

    } 
     
    public Station getStation_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Station where flag=0 and idstation = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((Station) list.get(0));
        }
    }
  public Station getStation_by_id(int id, String suffix) {
                       Session session  =  HibernateUtil.getSessionFactory().openSession();

        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Station where flag=0 and idstation = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((Station) list.get(0));
        }
    }
    public List getUserInfo_by_stationType(Session session, StationType stationType, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Station where flag=0 and stationType = " + stationType.getIdstationType(), suffix);

    }

    public List getUserInfo_by_trader(Session session, Trader trader, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Station where flag=0 and trader = " + trader.getIdtrader(), suffix);

    }
   public List getStations_by_trader( Trader trader, String suffix) {
        Session session  =  HibernateUtil.getSessionFactory().openSession();
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Station where flag=0 and trader = " + trader.getIdtrader(), suffix);

    }
     public List getStations_by_trader(Session session , Trader trader, String suffix) {
       
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Station where flag=0 and trader = " + trader.getIdtrader(), suffix);

    }
    public List getUserInfo_by_username(Session session, String username, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Station where flag=0 "
                + "and username LIKE '%" + username + "%'",
                suffix);
    }

    public List getUserInfo_by_trader_stationType(Session session, Trader trader, StationType stationType, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Station where flag=0 "
                + " and trader = " + trader.getIdtrader()
                + " and stationType = " + stationType.getIdstationType() + "",
                suffix);
    }
    
  
    public List getUserInfo_by_trader_status(Session session, Trader trader, StatusInfo status, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Station where flag=0 "
                + " and trader = " + trader.getIdtrader()
                + " and statusInfo = " + status.getIdstatusInfo() + "",
                suffix);
    }
    
  

    public void addStation(Station adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updateStation(Station adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }
}
