package model_helpers;

import java.util.List;
import model_db.StatusInfo;
import model_util.HibernateUtil;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;

/**
 * StatusInfo generated by hbm2java
 */
public class StatusInfo_Util {

    public List getAllStatusInfo(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM StatusInfo where flag=0", suffix);

    }
 public List getAllStatusInfo(String suffix) {
        Session session  =  HibernateUtil.getSessionFactory().openSession();
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM StatusInfo where flag=0", suffix);

    }

    public StatusInfo getStatusInfo_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM StatusInfo where flag=0 and idstatusInfo = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((StatusInfo) list.get(0));
        }
    }

    public List getStatusInfo_by_statusInfoDesc_Like(Session session, String statusInfoDesc, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM StatusInfo where flag=0 and statusInfoDesc LIKE '%" + statusInfoDesc + "%'", suffix);
    }
 public List getStatusInfo_by_statusInfoDesc_Like( String statusInfoDesc, String suffix) {
             Session session  =  HibernateUtil.getSessionFactory().openSession();

        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM StatusInfo where flag=0 and statusInfoDesc LIKE '%" + statusInfoDesc + "%'", suffix);
    }
    
    public StatusInfo getStatusInfo_by_statusInfoDesc(Session session, String statusInfoDesc, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM StatusInfo where flag=0 and statusInfoDesc = '" + statusInfoDesc + "'", suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((StatusInfo) list.get(0));
        }
    }

    public void addOfferInfo(StatusInfo adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updateOfferInfo(StatusInfo adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }

}
