package model_helpers;

import java.util.List;
import model_db.StationType;
import model_util.HibernateUtil;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;


/**
 * SimType generated by hbm2java
 */
public class StationType_Util {

    public List getAllStationType(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM StationType where flag=0", suffix);

    }
    
   
   public List getAllStationType( String suffix) {
        Session session  =  HibernateUtil.getSessionFactory().openSession();
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM StationType where flag=0", suffix);

    }
    public StationType getStationType_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM StationType where flag=0 and idstationType = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((StationType) list.get(0));
        }
    }

    public List getStationType_by_StationTypeDesc_Like(Session session, String offerDesc, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM StationType where flag=0 and stationTypeDesc LIKE '%" + offerDesc + "%'", suffix);
    }
    
    public StationType getStationType_by_StationTypeDesc(Session session, String offerDesc, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM StationType where flag=0 and stationTypeDesc = '" + offerDesc + "'", suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((StationType) list.get(0));
        }
    }

    public void addStationType(StationType adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updateStationType(StationType adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }


}


