package model_helpers;

import java.util.List;
import model_db.TraderCategory;
import model_util.HibernateUtil;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;

/**
 * TraderCategory generated by hbm2java
 */
public class TraderCategory_Util {

    public List getAllTraderCategory(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TraderCategory where flag=0", suffix);

    }



    public List getAllTraderCategory(String suffix) {
        Session globalSession = HibernateUtil.getSessionFactory().openSession();

        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(globalSession, "FROM TraderCategory where flag=0", suffix);

    }

    public TraderCategory getTraderCategory_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TraderCategory where flag=0 and idtraderCategory = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((TraderCategory) list.get(0));
        }
    }

    public List getTraderCategory_by_traderCategoryDesc_Like(Session session, String traderCategoryDesc, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TraderCategory where flag=0 and traderCategoryDesc LIKE '%" + traderCategoryDesc + "%'", suffix);
    }

    public TraderCategory getTraderCategory_by_traderCategoryDesc(Session session, String traderCategoryDesc, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TraderCategory where flag=0 and traderCategoryDesc = '" + traderCategoryDesc + "'", suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((TraderCategory) list.get(0));
        }
    }

    public void addTraderCategory(TraderCategory adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updatTraderCategory(TraderCategory adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }

}
