package model_helpers;

import java.util.List;
import model_db.TraderType;
import model_util.HibernateUtil;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;

/**
 * TraderType generated by hbm2java
 */
public class TraderType_Util {

    public List getAllTraderType(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TraderType where flag=0", suffix);

    }
 public List getAllTraderType( String suffix) {
        Session globalSession = HibernateUtil.getSessionFactory().openSession();

        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(globalSession, "FROM TraderType where flag=0", suffix);

    }
    public TraderType geTraderType_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TraderType where flag=0 and idtraderType = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((TraderType) list.get(0));
        }
    }

    public List getTraderType_by_traderTypeDesc_Like(Session session, String traderTypeDesc, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TraderType where flag=0 and traderTypeDesc LIKE '%" + traderTypeDesc + "%'", suffix);
    }

    public TraderType getTraderType_by_traderTypeDesc(Session session, String traderTypeDesc, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TraderType where flag=0 and traderTypeDesc = '" + traderTypeDesc + "'", suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((TraderType) list.get(0));
        }
    }

    public void addTraderType(TraderType adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updatTraderType(TraderType adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }

}
