package model_helpers;

import java.util.List;
import model_db.StatusInfo;
import model_db.Trader;
import model_db.TraderCategory;
import model_db.TraderType;
import model_util.HibernateUtil;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;

/**
 * Trader generated by hbm2java
 */
public class Trader_Util  {

     public List getAllTrader(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0", suffix);

    }
  public List getAllTrader( String suffix) {
                  Session globalSession  =  HibernateUtil.getSessionFactory().openSession();

        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(globalSession, "FROM Trader where flag=0", suffix);

    }
    public Trader getTradfer_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 and idtrader = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((Trader) list.get(0));
        }
    }

    
      public Trader getTradfer_by_id(int id, String suffix) {
        Session session  =  HibernateUtil.getSessionFactory().openSession();
        
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 and idtrader = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((Trader) list.get(0));
        }
    }

    
    public List getTrader_by_statusInfo(Session session, StatusInfo statusInfo, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 and statusInfo = " + statusInfo.getIdstatusInfo(), suffix);

    }

    public List getTrader_by_traderCategory(Session session, TraderCategory traderCategory, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 and traderCategory = " + traderCategory.getIdtraderCategory(), suffix);

    }
    
    public List getTrader_by_traderType(Session session, TraderType traderType, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 and traderType = " + traderType.getIdtraderType(), suffix);

    }
    public List getTrader_by_traderType_and_Category(Session session, TraderType traderType, TraderCategory traderCategory, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 "
                + "and traderType = " + traderType.getIdtraderType() 
                + " and traderCategory = " + traderCategory.getIdtraderCategory(), 
                suffix);

    }
    public List getTrader_by_trader_grossiste(  String suffix) {
         Session session  =  HibernateUtil.getSessionFactory().openSession();
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 "
                + "and traderType = 1"  
                + " and traderCategory = 1" , 
                suffix);

    }
    public List getTrader_by_fullname(Session session, String traderFname, String traderLname, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 "
                + "and traderFname LIKE '%" + traderFname + "%'" 
                + "and traderLname LIKE '%" + traderLname + "%'", 
                suffix);
    }
    
    public List getTrader_by_firstname(Session session, String traderFname, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 "
                + "and traderFname LIKE '%" + traderFname + "%'", 
                suffix);
    }
    
    
    public List getTrader_by_lastname(Session session, String traderLname, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 "
                + "and traderLname LIKE '%" + traderLname + "%'", 
                suffix);
    }
    
    public List getTrader_by_traderCompany(Session session, String traderCompany, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 "
                + "and traderCompany = '" + traderCompany + "'", 
                suffix);
    }
    
    public List getTrader_by_name_wilaya(Session session, String traderFname, String traderLname, String wilaya, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 "
                + "and traderFname LIKE '%" + traderFname + "%'" 
                + "and traderLname LIKE '%" + traderLname + "%'" 
                + "and wilaya LIKE '%" + wilaya + "%'", 
                suffix);
    }

    
    public List getTrader_by_name_wilaya_commune(Session session, String traderFname, String traderLname, String wilaya, String commune, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 "
                + "and traderFname LIKE '%" + traderFname + "%'" 
                + "and traderLname LIKE '%" + traderLname + "%'" 
                + "and commune LIKE '%" + commune + "%'" 
                + "and wilaya LIKE '%" + wilaya + "%'", 
                suffix);
    }
    
    public List getTrader_by_wilaya_commune(Session session, String traderFname, String traderLname, String wilaya, String commune, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 "
                + "and commune LIKE '%" + commune + "%'" 
                + "and wilaya LIKE '%" + wilaya + "%'", 
                suffix);
    }
    
    public List getTrader_by_wilaya(Session session, String traderFname, String traderLname, String wilaya, String commune, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM Trader where flag=0 "
                + "and wilaya LIKE '%" + wilaya + "%'", 
                suffix);
    }
    
    public void addTrader(Trader adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updateTrader(Trader adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }

}


