package model_helpers;

import java.util.List;
import model_db.SimOffer;
import model_db.StatusInfo;
import model_db.TransactionTopup;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;

/**
 * TransactionTopup generated by hbm2java
 */
public class TransactionTopup_Util {

    public List getAllTransactionTopup(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TransactionTopup where flag=0", suffix);

    }

    public TransactionTopup getTransactionTopup_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TransactionTopup where flag=0 and idtransacttopup = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((TransactionTopup) list.get(0));
        }
    }

    public List getTransactionTopup_by_simOffer(Session session, SimOffer simOffer, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TransactionTopup where flag=0 "
                + "and simOffer = " + simOffer.getIdsimOffer(), suffix);

    }

    public List getTransactionTopup_by_statusInfo(Session session, StatusInfo statusInfo, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TransactionTopup where flag=0 "
                + "and statusInfo = " + statusInfo.getIdstatusInfo(), suffix);

    }

    public List getTransactionTopup_by_simClient(Session session, String simClient, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TransactionTopup where flag=0 "
                + "and simInfo LIKE '%" + simClient + "%'", suffix);

    }

    public List getTransactionTopup_by_transactAmount(Session session, double transactAmountmin, double transactAmountmax, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TransactionTopup where flag=0 "
                + "and (transactAmount >= " + transactAmountmin + " and transactAmount <= " + transactAmountmax + ")",
                suffix);
    }

    public List getTransactionTopup_by_realTransactAmount(Session session, double realtransactAmountmin, double realtransactAmountmax, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TransactionTopup where flag=0 "
                + "and (realTransactAmount >= " + realtransactAmountmin + " and realTransactAmount <= " + realtransactAmountmax + ")",
                suffix);
    }

    public List getTransactionTopup_by_simOffer_statusInfo(Session session, SimOffer simOffer, StatusInfo statusInfo, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TransactionTopup where flag=0 "
                + "and simOffer = " + simOffer.getIdsimOffer()
                + " and statusInfo = " + statusInfo.getIdstatusInfo(),
                suffix);

    }

    public List getTransactionTopup_by_simOffer_statusInfo_transactAmount(Session session, SimOffer simOffer, StatusInfo statusInfo, double transactAmountmin, double transactAmountmax, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TransactionTopup where flag=0 "
                + "and simOffer = " + simOffer.getIdsimOffer()
                + " and statusInfo = " + statusInfo.getIdstatusInfo()
                + " and (transactAmount >= " + transactAmountmin + " and transactAmount <= " + transactAmountmax + ")",
                suffix);

    }

    public List getTransactionTopup_by_simOffer_statusInfo_realtransactAmount(Session session, SimOffer simOffer, StatusInfo statusInfo, double transactAmountmin, double transactAmountmax, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TransactionTopup where flag=0 "
                + "and simOffer = " + simOffer.getIdsimOffer()
                + " and statusInfo = " + statusInfo.getIdstatusInfo()
                + " and (realTransactAmount >= " + transactAmountmin + " and realTransactAmount <= " + transactAmountmax + ")",
                suffix);

    }

    public List getTransactionTopup_by_simInfo_transactAmount(Session session, SimOffer simOffer, double transactAmountmin, double transactAmountmax, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TransactionTopup where flag=0 "
                + "and simOffer = " + simOffer.getIdsimOffer()
                + " and (transactAmount >= " + transactAmountmin + " and transactAmount <= " + transactAmountmax + ")",
                suffix);

    }

    public List getTransactionTopup_by_simOffer_realtransactAmount(Session session, SimOffer simOffer, double transactAmountmin, double transactAmountmax, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM TransactionTopup where flag=0 "
                + "and simOffer = " + simOffer.getIdsimOffer()
                + " and (realTransactAmount >= " + transactAmountmin + " and realTransactAmount <= " + transactAmountmax + ")",
                suffix);
    }

    public void addTransactionTopup(TransactionTopup adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updateTransactionTopup(TransactionTopup adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }
}
