package model_helpers;

import java.util.List;
import model_db.UserCategory;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;

/**
 * UserCategory generated by hbm2java
 */
public class UserCategory_Util {

    public List getAllUserCategory(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM UserCategory where flag=0", suffix);

    }

    public UserCategory getUserCategory_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM UserCategory where flag=0 and iduserCategory = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((UserCategory) list.get(0));
        }
    }

    public List getUserCategory_by_offerTypeDesc_Like(Session session, String offerDesc, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM UserCategory where flag=0 and userCategoryDesc LIKE '%" + offerDesc + "%'", suffix);
    }

    public UserCategory getUserCategory_by_UserCategoryDesc(Session session, String offerDesc, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM UserCategory where flag=0 and userCategoryDesc = '" + offerDesc + "'", suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((UserCategory) list.get(0));
        }
    }

    public void addOfferInfo(UserCategory adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updateOfferInfo(UserCategory adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }

}
