package model_helpers;

import java.util.List;
import model_db.Trader;
import model_db.UserCategory;
import model_db.UserInfo;
import model_util.HibernateUtil;
import model_util.hqlQueriesHelper;
import org.hibernate.Session;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo_Util {

    public List getAllUserInfo(Session session, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM UserInfo where flag=0", suffix);

    }

    public UserInfo getUserInfo_by_id(Session session, int id, String suffix) {
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM UserInfo where flag=0 and iduserInfo = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((UserInfo) list.get(0));
        }
    }

      public UserInfo getUserInfo_by_id( int id, String suffix) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        List list = hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM UserInfo where flag=0 and iduserInfo = " + id, suffix);
        if (list.isEmpty()) {
            return null;
        } else {
            return ((UserInfo) list.get(0));
        }
    }
    
    public List getUserInfo_by_userCategory(Session session, UserCategory userCategory, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM UserInfo where flag=0 and userCategory = " + userCategory.getIduserCategory(), suffix);

    }

    public List getUserInfo_by_trader(Session session, Trader trader, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM UserInfo where flag=0 and trader = " + trader.getIdtrader(), suffix);

    }

    public List getUserInfo_by_username(Session session, String username, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM UserInfo where flag=0 "
                + "and username LIKE '%" + username + "%'",
                suffix);
    }

    public List getUserInfo_by_trader_username(Session session, Trader trader, String username, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM UserInfo where flag=0 "
                + " and trader = " + trader.getIdtrader()
                + " and username LIKE '%" + username + "%'",
                suffix);
    }
    
    public List getUserInfo_by_username_password(Session session, String username, String password, String suffix) {
        return hqlQueriesHelper.ExecuteSelectHqlQuery_WithPreparedSession(session, "FROM UserInfo where flag=0 "
                + " and username = '" + username+"'"
                + " and password = '" + password+"'",
                suffix);
    }

    public void addUserInfo(UserInfo adt, Session session) {
        hqlQueriesHelper.executeAddHQLQuery_WithPreparedSession(adt, session);
    }

    public void updateUserInfo(UserInfo adt, Session session) {
        hqlQueriesHelper.executeUpdateHQLQuery_WithPreparedSession(adt, session);
    }
}
